server:
  port: 8080

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            backend-service:
              - uri: https://service-1-0k83.onrender.com
              - uri: https://service-2-7sfz.onrender.com
              - uri: https://service-3-tlij.onrender.com
    gateway:
      mvc:
        routes:
          - id: backend-service
            uri: lb://backend-service
            predicates:
              - Path=/api/**