server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-1
            uri: https://service-1-0k83.onrender.com
            predicates:
              - Path=/api/**
          - id: backend-2
            uri: https://service-2-7sfz.onrender.com
            predicates:
              - Path=/api/**
          - id: backend-3
            uri: https://service-3-tlij.onrender.com
            predicates:
              - Path=/api/**