server:
  port: 8080

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            frontend-ui:
              - uri: https://linksphere-frontend-service-1.onrender.com
              - uri: https://linksphere-frontend-service-2.onrender.com
    gateway:
      mvc:
        routes:
          - id: frontend-ui
            uri: lb://frontend-ui
            predicates:
              - Path=/**
            filters:
              - name: CircuitBreaker
                args:
                  name: backendCircuitBreaker
                  fallbackUri: forward:/api/fallback