name: Keep Frontend Gateway Active

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: curl -f ${{ secrets.GATEWAY_FRONTEND_URL }} 
